# Generated by Django 4.2.1 on 2023-05-14 21:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('image', models.ImageField(upload_to='media')),
                ('urgency', models.IntegerField(choices=[(1, 'Urgent'), (2, 'Needs to be adopted soon'), (3, 'Not urgent')], default=3)),
                ('description', models.CharField(max_length=10000)),
                ('status', models.IntegerField(choices=[(1, 'Available'), (2, 'Adopted'), (3, 'Euthanized')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('email', models.CharField(max_length=30)),
                ('phone', models.CharField(default='', max_length=10)),
                ('password', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('salt', models.CharField(max_length=1023)),
            ],
        ),
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=30)),
                ('phone', models.CharField(default='', max_length=10)),
                ('address', models.CharField(max_length=60, unique=True)),
                ('city', models.CharField(default='', max_length=60)),
                ('additional_info', models.CharField(blank=True, max_length=300)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='shelters', to='project.user')),
            ],
        ),
        migrations.CreateModel(
            name='Euthanization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('dog', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='euthanizations', to='project.dog')),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=60)),
                ('city', models.CharField(default='', max_length=60)),
                ('time_range', models.CharField(max_length=60)),
                ('condition', models.CharField(max_length=300)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='project.user')),
            ],
        ),
        migrations.AddField(
            model_name='dog',
            name='shelter',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='dogs', to='project.shelter'),
        ),
        migrations.AddField(
            model_name='dog',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='dogs', to='project.user'),
        ),
        migrations.CreateModel(
            name='Adoption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('dog', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='adoptions', to='project.dog')),
            ],
        ),
    ]
